version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    image: mikaalaoutinen/desdeo-frontend
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app